---
title: "CASA0010 Dissertation"
author: Andrew MacLachlan 
description: Between 2019 and 2021 I led the CASA dissertation module and I continue to supervise students annually. It is based around the writing and preparation of an original research project in the form of a Master's Dissertation.
categories: [templates, dissertation, supervision, MSc, UCL]
slug: CASA0010
---

## Supervision with me

For the students I supervise my expectations are:

* Attendance and engagement at 5 in-person sessions (detailed below)

* Submission of homework before the in-person sessions

* Regular submission of written work for review

* Students must request individual meetings (if required) sharing the following at least 3 working days before the meeting:
  * Some work (e.g. writing, results, figures)
  * An agenda (e.g. specific topics or questions for discussion)
  
* Submission of a nearly complete draft thesis by the circulated deadline 

## Sessions

The structured sessions are in two parts: 1. Preparing for a thesis and 2. Writing a thesis. 

### Part 1: Preparing for a thesis

Here, two separate lectures are delivered, namely:

-   Studying for a dissertation: [<i class="fa-solid fa-person-chalkboard fa-1.5x"> </i>](https://andrewmaclachlan.github.io/CASAdissertation-studying-for-a-dissertation/#1)

-   Thesis study: [<i class="fa-solid fa-person-chalkboard fa-1.5x"> </i>](https://andrewmaclachlan.github.io/CASAdissertation-thesis-study/#1)


### Part 2: Writing a thesis 
  
Here we explore two previous dissertation submissions, one scoring a distinction and the other a pass. Across three sessions we progress through different parts of the thesis (list below). In each session we create a table for both previous submissions for comparison in relation to the marking scheme. At the end of the sessions students must place their work within these tables. 

- Introduction and literature review 
  - Table headings: Problem, Aim/Question, Objectives, Literature review
- Methodology and Results 
  - Table headings: Data, Methods, Assumptions, Support (literature), Outputs
- Discussion and Conclusion 
  - Table headings: Implications, Context, Methods (transferability), Broader context, Limitations

**Additional resources:**

-   [Recommended thesis structure](https://github.com/andrewmaclachlan/website/blob/main/Teach/CASA0010/Thesis%20structure.docx)

## Projects

### Safety in the built envrionment

Perceived safety in the built envrionment. A few years ago a student asked particpants to walk a set route whilst monitoring their heart rate and completing a survey at the end of each road. This would extend that work by looking into the routes different groups take when given only a start and end point  

  Data:
  
  * Participants could wear Heart Rate devices (e.g. fitbits)
  * GPS trackers
  * Open street map for features of the built environment 
  
  Possible methods:
  
  * Any method that could predict how safe participants feel (e.g. regression, machine learing)

  Main challenge:
  
  * Risk assessment for data collection
  * Analysis on small data set
  
### Remotely monitoring pollution from EO data / assessing effectivness of restrictions.

Have low emissions zones been successful in reducing air pollution. This could be for any city and it would be possible to draw comparsion to the success of Paris. 

  Data:
  
  * Ideally Sentinel 5P data via Google Earth Engine
  * Could be supplemented with weather station data
  
  Methods:
  
  * Any that can detect trends at the pixel level. This could include a t-test (e.g. similar to Ollie's work) or a Mann Kendall test
  * Once areas that have changed are identified then these could be used to check or validate low emission rules within the pixels. 
  
  Main challenge: 
  
  * Determining when different low emission zones were implemented across the city
    
### Accessibility to gambling shops and mental health

This would explore accessibility to gamling shops for different communities, if there is a relationship to other shops (e.g. fast food) and if there is relationship to mental health outcomes. This could really be for any city, assuming data is available. 

  Data:
  
  * Open Street Map for shop locations
  * Census of other similar data for health

  Methods:
  
  * R5R - accessibility model that accounts for public transport
  * some prediction method (e.g. regression, ML)
  
  Main challenge:
  
  * nothing obvious
  
### Exploring people vs car priorities across the city

This project explores where people or cars have preference in the city, why that might be and where there is either an inbalance. Notably, where i live there is an intersection that cars can progress after a single light, but pedestrians have to cross four separate lights. 

  Data:
  
  * Open street map
  * Could include some field work (e.g. monitoring specific intersections)
  
  Main challenge:
  
  * needs refinement of the topic / quesiton.
  
  
### Other methods / data

I am interested in any projects that condiser using the following methods or data which i can provide assistance with:

Methods:

* R5R - accessibility
* Google Earth Engine
* PostGIS
  
Data:

* Open Police (USA): https://openpolicing.stanford.edu/data/ 
* Water point data: https://www.waterpointdata.org/access-data/. See conference abstract for reference: https://zenodo.org/records/10926688 
* Redlining boundaries: https://dsl.richmond.edu/panorama/redlining/data 
* Places health data, census tract (USA): https://data.cdc.gov/browse?category=500+Cities+%26+Places
* Stop, Question, Frisk (USA): https://www1.nyc.gov/site/nypd/stats/reports-analysis/stopfrisk.page



```{r, eval=FALSE, echo=FALSE}
**Module information**

Students will be required to plan the research and dissertation from an early stage with ongoing development building on both projects and taught courses developed through the year. The research topic will be defined under the guidance of the student's dissertation supervisor and with the support of the Programme Director. The aim is to produce a unique, individual piece of work with an emphasis on data collection, analysis and visualisation linked to policy and social science orientated applications.

Students may have an opportunity to collaborate with industry partners in this module.

```

